### ISSUE TITLE
Script External Load Error

### ISSUE THREAD

**Issue by camilocsotm** [tishanmadawa/Nx-React-MicroFrontend#1]
When I run the"npm run start" there is a point when I go to the http://localhost:4200/ and load scripts, this happens:
![image](https://user-images.githubusercontent.com/93563573/141174764-eeb142f2-bffa-4c8c-9ce3-32ea09fe1b45.png)

ScriptExternalLoadError
Loading script failed.
(error: http://localhost:4201/remoteEntry.js)
while loading "./MarketingApp" from 8211
Call Stack
 8211
  main.js:368:25
 Object.options.factory
  main.js:1135:31
 __webpack_require__
  main.js:410:33
 handleFunction
  main.js:656:31
 undefined
  main.js:675:15
 Object.__webpack_require__.f.remotes
  main.js:638:36
 undefined
  main.js:496:40
 Function.__webpack_require__.e
  main.js:495:67
× Close

**Comment by tishanmadawa** [comment]
**### Code updated.**  
Sorry for delay response. need to run applications separately.  
```
   nx run host:serve
   nx run remote:serve
```

If not you can install concurrently library globally and run  npm start
